### ISSUE TITLE
Q: how to load this as development folder in Plugin Loader?

### ISSUE THREAD

**Issue by skybleu** [Allen-Wrench/CreativeWorldSave#4]
I feel this plugin as pretty much essential when joining a new server that I plan to use long-term - it helps me create creative mode save to design and test blueprints to be used in given server.
Would it be possible to enhance README with steps that allow this plugin to be used with Plugin Loader, even after it was removed from official list of mods?

**Comment by Allen-Wrench** [comment]
I think it was taken off the plugin hub because it wasn't working for some reason or another... I've been taking a break from SE so I never got around to fixing it. 

Let me see if I can get it fixed and ill just upload the compiled binary here for you. Then you can just put the .dll into the ../Space Engineers/Bin64/Plugins folder and it should show up as a local plugin. Otherwise you would have to compile the code yourself before the plugin loader could use it.

**Comment by Allen-Wrench** [comment]
Try the updated plugin, i've included a compiled binary if you are unable to compile it yourself. You might have to right click the .dll and go into properties and check the box at the bottom to unblock the file or the plugin loader will not load it and crash.

**Comment by skybleu** [comment]
Sorry for no response, by the time you answered I got it working with older version.
Plugin was taken off Plugin Manager list because some people considered it 'cheating' because it exported more than they expected or sth, maybe it's worth to try  push it through again?
Only recently that version stopped working, but I'm happy to report the one from 3 wks ago works flawlessly.
Thanks for your hard work! I feel this plugin is godsend when trying to create blueprints for some servers.

**Comment by Allen-Wrench** [comment]
Glad to hear the updated version is working for you :) I probably wont bother getting it added back to the plugin loader for the time being. I haven't had a whole lot of free time lately because of work, but once I get some time to work on it ill figure something out.
