### ISSUE TITLE
Permission to list on pluginhub

### ISSUE THREAD

**Issue by jrloken** [Allen-Wrench/CreativeWorldSave#5]
@Allen-Wrench thanks for the fix! and the new interface 🙂 I was away from the game for a bit but getting back into it now.  Would you mind if I submit this to pluginhub for plugin loader?  Many servers/communities have adopted a rule that plugins not listed on pluginhub are against the rules

**Comment by Allen-Wrench** [comment]
It was already on the plugin hub in the past, but was taken off while I was away for some reason I can't remember. Someone probably complained about it, but who knows. In order to get it back onto the plugin hub, there were some changes that would have to be made which in my opinion sort of defeat the purpose of the plugin (changing location of planets, randomizing the world seed so asteroids would show up in different places, etc.) Things I don't plan on changing for the time being.

The nice thing about plugins though, is that they are 100% client side. So it really doesn't matter what opinions servers/communities adopt. What they don't know wont hurt them :)

**Comment by Allen-Wrench** [comment]
oh, and as a side note, the current version here on github conflicts with the nexus seamless plugin, so you would have to temporarily disable that plugin if you want to use this until I update github with a better version.

**Comment by jrloken** [comment]
Ah ok, I thought it was removed from pluginhub because of a crash.  If the seamless incompatibility bothers me I may take a crack at a fix.  Will send a PR if I do.  I was hoping to have it listed so I could promote it within my faction but if it's a grey area maybe not

**Comment by Allen-Wrench** [comment]
I updated github with the version that will work with seamless enabled, just had to patch in to a different method to hook the button click.
